src/components/scs/ScSheet/ScRow.js, src/components/scs/ScTabs.js
- fixed layout of categories workQuality and workEfficiency on request from product owner
=> fixed layout

src/components/admin/automationRules/AutomationRulesContainer.js
bugfix/PR-1219: Revert button fixed on page load
=> bugfix/PR-1219: Revert button fixed on page load

src/calls/admin.js, src/components/admin/UserRolesMenu.js, src/components/sidebar/Sidebar.js, src/translations/de.json, src/translations/en.json
feature/SP-23-roles-management: Roles Tab ready for PD.
=> feature/SP-23-roles-management: Roles Tab ready for PD.

src/calls/admin.js, src/components/scs/ScSheet/scTypes/ScSheetWithPr.js, src/components/scs/ScSheet/scTypes/ScSheetWithoutPr.js, src/helper/wrapping.js
bugfix/SP-49: Undefined percentage in SC Sheet after save fixed.
=> bugfix/SP-49: Undefined percentage in SC Sheet after save fixed.

src/components/scs/ownScs/OwnScsContainer.js, src/components/scs/processingScs/ProcessingScContainer.js, src/helper/string.js
bugfix/SP-52: Statuses in SC overview fixed.
=> bugfix/SP-52: Statuses in SC overview fixed.

src/components/scs/ScDetailInformation.js
feature/SP-16: Automated behavior of automated rules ready.
=> feature/SP-16: Automated behavior of automated rules ready.

src/components/sidebar/Sidebar.js
feature/SP-80: Eigene Scorecards Tab added.
=> feature/SP-80: Eigene Scorecards Tab added, Fis-sync log fixed.

.env.production, .env.test, Dockerfile, Jenkinsfile, deploy_utils/Jenkinsfile_deploy
build upgrade using docker layers
=> build upgrade

src/components/scs/ScSheet/ButtonsBelowSheet.js, src/components/scs/ScSheet/FinalScoreSection.js, src/components/scs/ScSheet/evaluationsCheck.js, src/components/scs/ScSheet/scTypes/ScSheetWithPr.js, src/components/scs/ScSheet/scTypes/ScSheetWithoutPr.js, src/components/scs/ScSheet/sumarize/MixedScRow.js, src/components/scs/ScSheet/sumarize/SummaryViewWithPr.js, src/components/scs/ScSheet/sumarize/SummaryViewWithoutPr.js, src/components/scs/scContainer/ScTypeToChoose.js, src/components/scs/scContainer/StatusStepper.js, src/translations/de.json
bugfix/SP-99-101-112: Fixed bugs: SP-74, SP-99, SP-101, SP-112
=> bugfix/SP-99-101-112: Fixed bugs: SP-74, SP-99, SP-101, SP-112

deploy_utils/Jenkinsfile_deploy
hotfix/noticket-deploy-fix: Deploy fixed
=> hotfix/noticket-deploy-fix: Deploy fixed

src/calls/employees.js, src/components/AllEmployees/ActiveEmployeesContainer.js, src/components/AllEmployees/EmployeesTable/ActiveEmployeesTable.js, src/components/admin/dbPatch/DatabasePatchesPanel.js
feature/SP-139: Active MA Tab updated.
=> feature/SP-139: Active MA Tab updated.

src/components/App.js, src/components/dashboard/Dashboard.js, src/components/dashboard/PlannedLeavings/PlannedLeavingsDialog.js, src/components/dashboard/newEmployees/NewEmployeesDialog.js, src/components/dashboard/newEmployees/NewEmployeesTable.js, src/components/sidebar/Sidebar.js
feature/SP-109-full-FIS-sync: ready.
=> feature/SP-109-full-FIS-sync: ready.

src/components/AllEmployees/EmployeeScsTable.js, src/helper/date.js, src/helper/filterData.js, src/translations/de.json
- removed time from employee's SCs dialog
- added filter option 'Keine SC erstellt'
=> SP-200 SP-204

src/components/scs/processingScs/ProcessingScContainer.js, src/components/scs/processingScs/ScTableHead.js, src/helper/filterFunctions.js
=> feature/SP-225: hotfix.

src/components/AllEmployees/EmployeeScsTable.js, src/components/dashboard/PlannedLeavings/PlannedLeavingsTable.js, src/components/dashboard/newEmployees/NewEmployeesTable.js
- fixed rest of the columns in employee SCs dialog
- fixed new employees table
- fixed planned leavings table
=> SP-238: fix rest of the columns and tables

src/translations/de.json
hotfix/sc-init-submit-tooltip-change: ready.
=> hotfix/sc-init-submit-tooltip-change: ready.

src/components/admin/automationRules/RuleItemPopup.js
feature/SP-247: Autorules SC period name validation added.
=> feature/SP-247: Autorules SC period name validation added.

src/components/admin/UserRolesPanel.js, src/components/dashboard/newEmployees/NewEmployeesTable.js, src/translations/de.json
bugfix/SP-260,261,262 - bugs fixed.
=> bugfix/SP-260,261,262 - bugs fixed.

src/components/AllEmployees/ActiveEmployeesContainer.js, src/components/AllEmployees/EmployeeScsDialog.js, src/components/AllEmployees/FormerEmployeesContainer.js, src/components/scs/ScSheet/ScRow.js, src/components/scs/ScSheet/ScRows.js, src/components/scs/processingScs/ProcessingScContainer.js
bugfix/SP-271,267,272 - bugs fixed.
=> bugfix/SP-271,267,272 - bugs fixed.

src/components/dashboard/ScsInProgressDialog/ScsDialog.js, src/components/filterComponents/FilteredValuesViewer.js, src/components/filterComponents/SearchFilter.js, src/components/filterComponents/SortingFilter.js, src/components/filterComponents/UpperFilterMenu.js
feature/SP-266-advanced-filter-changes: ready, implemented also SP-26.
=> feature/SP-266-advanced-filter-changes: ready, implemented also SP-26.

src/components/admin/automationRules/IgnoreListTable.js, src/components/dashboard/Dashboard.js
bugfix/SP-280: Styling bugs fixed.
=> bugfix/SP-280: Styling bugs fixed.

src/components/scs/ScSheet/scTypes/ScSheetWithPr.js, src/components/scs/ScSheet/scTypes/ScSheetWithoutPr.js, src/components/scs/scContainer/ScTypeToChoose.js
bugfix/SP-277-tooltip-and-bugs: fixed:
- Error msg in case of publishing SC changes
- tooltip in Submit button in init phase
- count of opened SCs for employee fixed in case there are some in init phase
=> bugfix/SP-277-tooltip-and-bugs: fixed.
